### ISSUE TITLE
Travis-ci module used is becoming deprecated

### ISSUE THREAD

**Issue by matt-oc** [nodezoo/nodezoo-travis#28]

**Comment by mcdonnelldean** [comment]
@matt-oc Are there any alternatives?

**Comment by CodeWriterWriter** [comment]
I've just updated all the dependencies on the one we're using and left a pull request.
In the event we no longer use that, there is a smaller light weight one we could use, but it only ever returns 10 or so pieces of data, and we'd be locking ourselves in what we could get in the future.
It would also limit us if we wanted to do anything more than a get request to travis

**Comment by matt-oc** [comment]
@mcdonnelldean We can always just use our own updated version of our current module (which is very good) it would just need to be put into a safe repo. Updating the deps didnt break anything so its good to go.

**Comment by mcdonnelldean** [comment]
Can I have a link to the original?

**Comment by CodeWriterWriter** [comment]
https://github.com/pwmckenna/node-travis-ci

**Comment by mcdonnelldean** [comment]
That's a big module to take over @matt-oc @CodeWriterWriter. If you decide to take it over you need to rename it and publish the new named one to npm.

**Comment by matt-oc** [comment]
Pr was made to the original repo with updates and looks like it will be accepted once a few small changes have been made so we shouldn't have to take on this module.
